baseURL = "https://d5qrvu2ns4359.cloudfront.net/"
languageCode = "id-id"
title = "Blog Saya"
theme = "github.com/adityatelange/hugo-PaperMod"

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"
